# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_scsi"
    "sd_mod"
    "sr_mod"
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/92ecc08e-509f-4edc-ad66-2fbaba7ada20";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/64E6-3DEC";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/srv/media/main" = {
    device = "main";
    fsType = "zfs";
  };

  fileSystems."/srv/media/cia/data" = {
    device = "cia/data";
    fsType = "zfs";
  };

  fileSystems."/srv/media/cia/cache" = {
    device = "cia/cache";
    fsType = "zfs";
  };

  # fileSystems."/srv/media/nvme1/data" = {
  #   device = "nvme1/data";
  #   fsType = "zfs";
  # };

  fileSystems."/srv/media/blub/data" = {
    device = "blub/data";
    fsType = "zfs";
  };

  fileSystems."/srv/media/blub/cache" = {
    device = "blub/cache";
    fsType = "zfs";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
