gateway = "192.168.1.1"
network = "192.168.1.0/24"
virtual-network = "10.20.30.0/24"
dns = ["192.168.1.1"]

[devices.jupiter]
dns = "jupiter.home.5kw.li"
ip = "192.168.1.12"
vip = "10.20.30.5"

[devices.saturn]
dns = "saturn.home.5kw.li"
ip = "192.168.1.9"
vip = "10.20.30.2"

[devices.ceres]
dns = "ceres.home.5kw.li"
ip = "192.168.1.13"
vip = "10.20.30.4"

[devices.mars]
dns = "mars.home.5kw.li"
ip = "192.168.1.10"
vip = "10.20.30.1"
